//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemnantSaveGuardian.locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GameStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RemnantSaveGuardian.locales.GameStrings", typeof(GameStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandoned Ruins.
        /// </summary>
        public static string AbandonedRuins {
            get {
                return ResourceManager.GetString("AbandonedRuins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alchemist.
        /// </summary>
        public static string Alchemist {
            get {
                return ResourceManager.GetString("Alchemist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Father.
        /// </summary>
        public static string AllFatherStory {
            get {
                return ResourceManager.GetString("AllFatherStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butcher&apos;s Fetish.
        /// </summary>
        public static string Amulet_ButchersFetish {
            get {
                return ResourceManager.GetString("Amulet_ButchersFetish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chains of Amplification.
        /// </summary>
        public static string Amulet_ChainsOfAmplification {
            get {
                return ResourceManager.GetString("Amulet_ChainsOfAmplification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimue&apos;s Ribbon.
        /// </summary>
        public static string Amulet_NimuesRibbon {
            get {
                return ResourceManager.GetString("Amulet_NimuesRibbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archon.
        /// </summary>
        public static string Archon {
            get {
                return ResourceManager.GetString("Archon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string Armor_Body {
            get {
                return ResourceManager.GetString("Armor_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bruiser.
        /// </summary>
        public static string Armor_Challenger {
            get {
                return ResourceManager.GetString("Armor_Challenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gloves.
        /// </summary>
        public static string Armor_Gloves {
            get {
                return ResourceManager.GetString("Armor_Gloves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Noon.
        /// </summary>
        public static string Armor_Gunslinger {
            get {
                return ResourceManager.GetString("Armor_Gunslinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer.
        /// </summary>
        public static string Armor_Handler {
            get {
                return ResourceManager.GetString("Armor_Handler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        public static string Armor_Head {
            get {
                return ResourceManager.GetString("Armor_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nightstalker.
        /// </summary>
        public static string Armor_Hunter {
            get {
                return ResourceManager.GetString("Armor_Hunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legs.
        /// </summary>
        public static string Armor_Legs {
            get {
                return ResourceManager.GetString("Armor_Legs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Medic.
        /// </summary>
        public static string Armor_Medic {
            get {
                return ResourceManager.GetString("Armor_Medic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radiant.
        /// </summary>
        public static string Armor_Radiant {
            get {
                return ResourceManager.GetString("Armor_Radiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crown of the Red Prince.
        /// </summary>
        public static string Armor_RedPrince {
            get {
                return ResourceManager.GetString("Armor_RedPrince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void.
        /// </summary>
        public static string Armor_Void {
            get {
                return ResourceManager.GetString("Armor_Void", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asylum.
        /// </summary>
        public static string Asylum {
            get {
                return ResourceManager.GetString("Asylum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ripsaw.
        /// </summary>
        public static string AsylumChainsaw {
            get {
                return ResourceManager.GetString("AsylumChainsaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Asylum.
        /// </summary>
        public static string AsylumStory {
            get {
                return ResourceManager.GetString("AsylumStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth.
        /// </summary>
        public static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cathedral Of Omens.
        /// </summary>
        public static string CathedralOfOmens {
            get {
                return ResourceManager.GetString("CathedralOfOmens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenger.
        /// </summary>
        public static string Challenger {
            get {
                return ResourceManager.GetString("Challenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Clock Tower.
        /// </summary>
        public static string ClockTower {
            get {
                return ResourceManager.GetString("ClockTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dran City.
        /// </summary>
        public static string DranStarter {
            get {
                return ResourceManager.GetString("DranStarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endaira&apos;s End.
        /// </summary>
        public static string EndairasEnd {
            get {
                return ResourceManager.GetString("EndairasEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineer.
        /// </summary>
        public static string Engineer {
            get {
                return ResourceManager.GetString("Engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer.
        /// </summary>
        public static string Explorer {
            get {
                return ResourceManager.GetString("Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faelin.
        /// </summary>
        public static string FaelinFaerlin {
            get {
                return ResourceManager.GetString("FaelinFaerlin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faelin / Faerin.
        /// </summary>
        public static string FaelinFaerlin_POI {
            get {
                return ResourceManager.GetString("FaelinFaerlin_POI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faerin.
        /// </summary>
        public static string Faerin {
            get {
                return ResourceManager.GetString("Faerin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fae Shaman Ring.
        /// </summary>
        public static string FaeShamanRing {
            get {
                return ResourceManager.GetString("FaeShamanRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golden Halls.
        /// </summary>
        public static string FaeStarter {
            get {
                return ResourceManager.GetString("FaeStarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fae Warrior Ring.
        /// </summary>
        public static string FaeWarriorRing {
            get {
                return ResourceManager.GetString("FaeWarriorRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten Field.
        /// </summary>
        public static string ForgottenField {
            get {
                return ResourceManager.GetString("ForgottenField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimue&apos;s Retreat.
        /// </summary>
        public static string GoldenHall_Nimue {
            get {
                return ResourceManager.GetString("GoldenHall_Nimue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gunslinger.
        /// </summary>
        public static string Gunslinger {
            get {
                return ResourceManager.GetString("Gunslinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler.
        /// </summary>
        public static string Handler {
            get {
                return ResourceManager.GetString("Handler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter.
        /// </summary>
        public static string Hunter {
            get {
                return ResourceManager.GetString("Hunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imperial Gardens.
        /// </summary>
        public static string ImperialGardens {
            get {
                return ResourceManager.GetString("ImperialGardens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indignant Fetish.
        /// </summary>
        public static string IndignantFetish {
            get {
                return ResourceManager.GetString("IndignantFetish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invader.
        /// </summary>
        public static string Invader {
            get {
                return ResourceManager.GetString("Invader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaeula&apos;s Rest.
        /// </summary>
        public static string KaeulasRest {
            get {
                return ResourceManager.GetString("KaeulasRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koara Kuri Nest.
        /// </summary>
        public static string KoaraKuriNest {
            get {
                return ResourceManager.GetString("KoaraKuriNest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laemirs&apos; Lyceum.
        /// </summary>
        public static string LaemirsLyceum {
            get {
                return ResourceManager.GetString("LaemirsLyceum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medic.
        /// </summary>
        public static string Medic {
            get {
                return ResourceManager.GetString("Medic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nightweavers Web.
        /// </summary>
        public static string Nightweb {
            get {
                return ResourceManager.GetString("Nightweb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OverworldPOI.
        /// </summary>
        public static string OverworldPOI {
            get {
                return ResourceManager.GetString("OverworldPOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acid Stone.
        /// </summary>
        public static string Ring_AcidStone {
            get {
                return ResourceManager.GetString("Ring_AcidStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anastasia&apos;s Inspiration.
        /// </summary>
        public static string Ring_AnastasijasInspiration {
            get {
                return ResourceManager.GetString("Ring_AnastasijasInspiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booster Ring.
        /// </summary>
        public static string Ring_BoosterRing {
            get {
                return ResourceManager.GetString("Ring_BoosterRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex Ward.
        /// </summary>
        public static string Ring_HexWard {
            get {
                return ResourceManager.GetString("Ring_HexWard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul Link.
        /// </summary>
        public static string Ring_SoulLink {
            get {
                return ResourceManager.GetString("Ring_SoulLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream Coupler Ring.
        /// </summary>
        public static string Ring_StreamCoupler {
            get {
                return ResourceManager.GetString("Ring_StreamCoupler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        public static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ashen Wasteland.
        /// </summary>
        public static string RootEarthAshenWasteland {
            get {
                return ResourceManager.GetString("RootEarthAshenWasteland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupted Harbor.
        /// </summary>
        public static string RootEarthCorruptedHarbor {
            get {
                return ResourceManager.GetString("RootEarthCorruptedHarbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Nexus.
        /// </summary>
        public static string RootNexus {
            get {
                return ResourceManager.GetString("RootNexus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flooder Sewer.
        /// </summary>
        public static string Sewer {
            get {
                return ResourceManager.GetString("Sewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dungeon.
        /// </summary>
        public static string SideD {
            get {
                return ResourceManager.GetString("SideD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summoner.
        /// </summary>
        public static string Summoner {
            get {
                return ResourceManager.GetString("Summoner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tal&apos;Ratha.
        /// </summary>
        public static string TalRatha {
            get {
                return ResourceManager.GetString("TalRatha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TheTwistedChantry.
        /// </summary>
        public static string The_Twisted_Chantry {
            get {
                return ResourceManager.GetString("The Twisted Chantry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Custodian.
        /// </summary>
        public static string TheCustodian {
            get {
                return ResourceManager.GetString("TheCustodian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dappled Glade.
        /// </summary>
        public static string TheDappledGlade {
            get {
                return ResourceManager.GetString("TheDappledGlade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Expanding Glade.
        /// </summary>
        public static string TheExpandingGlade {
            get {
                return ResourceManager.GetString("TheExpandingGlade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lament.
        /// </summary>
        public static string TheLament {
            get {
                return ResourceManager.GetString("TheLament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Nameless Nest.
        /// </summary>
        public static string TheNamelessNest {
            get {
                return ResourceManager.GetString("TheNamelessNest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Postulant.
        /// </summary>
        public static string ThreeMenMorris {
            get {
                return ResourceManager.GetString("ThreeMenMorris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tormented Asylum.
        /// </summary>
        public static string TormentedAsylum {
            get {
                return ResourceManager.GetString("TormentedAsylum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tome of Knowledge.
        /// </summary>
        public static string TraitBook {
            get {
                return ResourceManager.GetString("TraitBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ward 13.
        /// </summary>
        public static string Ward13 {
            get {
                return ResourceManager.GetString("Ward13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth.
        /// </summary>
        public static string World_Earth {
            get {
                return ResourceManager.GetString("World_Earth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losomn.
        /// </summary>
        public static string World_Fae {
            get {
                return ResourceManager.GetString("World_Fae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaesha.
        /// </summary>
        public static string World_Jungle {
            get {
                return ResourceManager.GetString("World_Jungle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labyrinth.
        /// </summary>
        public static string World_Labyrinth {
            get {
                return ResourceManager.GetString("World_Labyrinth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N&apos;Erud.
        /// </summary>
        public static string World_Nerud {
            get {
                return ResourceManager.GetString("World_Nerud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Earth.
        /// </summary>
        public static string World_RootEarth {
            get {
                return ResourceManager.GetString("World_RootEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Boss.
        /// </summary>
        public static string WorldBoss {
            get {
                return ResourceManager.GetString("WorldBoss", resourceCulture);
            }
        }
    }
}
