//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemnantSaveGuardian.locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RemnantSaveGuardian.locales.GameStrings", typeof(GameStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth.
        /// </summary>
        internal static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booster Ring.
        /// </summary>
        internal static string BoosterRing {
            get {
                return ResourceManager.GetString("BoosterRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chains of Amplification.
        /// </summary>
        internal static string ChainsOfAmplification {
            get {
                return ResourceManager.GetString("ChainsOfAmplification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Clock Tower.
        /// </summary>
        internal static string ClockTower {
            get {
                return ResourceManager.GetString("ClockTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losomn.
        /// </summary>
        internal static string Fae {
            get {
                return ResourceManager.GetString("Fae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faelin / Faerin.
        /// </summary>
        internal static string FaelinFaerlin_POI {
            get {
                return ResourceManager.GetString("FaelinFaerlin_POI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fae Shaman Ring.
        /// </summary>
        internal static string FaeShamanRing {
            get {
                return ResourceManager.GetString("FaeShamanRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fae Warrior Ring.
        /// </summary>
        internal static string FaeWarriorRing {
            get {
                return ResourceManager.GetString("FaeWarriorRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indignant Fetish.
        /// </summary>
        internal static string IndignantFetish {
            get {
                return ResourceManager.GetString("IndignantFetish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaesha.
        /// </summary>
        internal static string Jungle {
            get {
                return ResourceManager.GetString("Jungle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labyrinth.
        /// </summary>
        internal static string Labyrinth {
            get {
                return ResourceManager.GetString("Labyrinth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth.
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N&apos;Erud.
        /// </summary>
        internal static string Nerud {
            get {
                return ResourceManager.GetString("Nerud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimue&apos;s Retreat.
        /// </summary>
        internal static string NimueDream {
            get {
                return ResourceManager.GetString("NimueDream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OverworldPOI.
        /// </summary>
        internal static string OverworldPOI {
            get {
                return ResourceManager.GetString("OverworldPOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dungeon.
        /// </summary>
        internal static string SIdeD {
            get {
                return ResourceManager.GetString("SIdeD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul Link.
        /// </summary>
        internal static string SoulLink {
            get {
                return ResourceManager.GetString("SoulLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream Coupler Ring.
        /// </summary>
        internal static string StreamCoupler {
            get {
                return ResourceManager.GetString("StreamCoupler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tome of Knowledge.
        /// </summary>
        internal static string TraitBook {
            get {
                return ResourceManager.GetString("TraitBook", resourceCulture);
            }
        }
    }
}
