//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remnant2SaveAnalyzer.locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Remnant2SaveAnalyzer.locales.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remnant 2 Save Analyzer.
        /// </summary>
        public static string AboutRSG {
            get {
                return ResourceManager.GetString("AboutRSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventure.
        /// </summary>
        public static string Adventure {
            get {
                return ResourceManager.GetString("Adventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always On Top.
        /// </summary>
        public static string Always_On_Top {
            get {
                return ResourceManager.GetString("Always On Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete backup {backupName}?.
        /// </summary>
        public static string Are_you_sure_you_want_to_delete_backup__backupName__ {
            get {
                return ResourceManager.GetString("Are you sure you want to delete backup {backupName}?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup completed.
        /// </summary>
        public static string Backup_completed {
            get {
                return ResourceManager.GetString("Backup completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup deleted.
        /// </summary>
        public static string Backup_deleted {
            get {
                return ResourceManager.GetString("Backup deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Folder.
        /// </summary>
        public static string Backup_Folder {
            get {
                return ResourceManager.GetString("Backup Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup folder not set; reverting to default..
        /// </summary>
        public static string Backup_folder_not_set__reverting_to_default_ {
            get {
                return ResourceManager.GetString("Backup folder not set; reverting to default.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup restored.
        /// </summary>
        public static string Backup_restored {
            get {
                return ResourceManager.GetString("Backup restored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups folder not found, creating....
        /// </summary>
        public static string Backups_folder_not_found__creating___ {
            get {
                return ResourceManager.GetString("Backups folder not found, creating...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups found.
        /// </summary>
        public static string Backups_found {
            get {
                return ResourceManager.GetString("Backups found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup current save.
        /// </summary>
        public static string btnBackup_ToolTip {
            get {
                return ResourceManager.GetString("btnBackup_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Now.
        /// </summary>
        public static string btnCheckUpdate_Content {
            get {
                return ResourceManager.GetString("btnCheckUpdate_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open backups folder.
        /// </summary>
        public static string btnOpenBackupsFolder_ToolTip {
            get {
                return ResourceManager.GetString("btnOpenBackupsFolder_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start game.
        /// </summary>
        public static string btnStartGame_ToolTip {
            get {
                return ResourceManager.GetString("btnStartGame_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign.
        /// </summary>
        public static string Campaign {
            get {
                return ResourceManager.GetString("Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        public static string Character {
            get {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically backup save files.
        /// </summary>
        public static string chkAutoBackup_Content {
            get {
                return ResourceManager.GetString("chkAutoBackup_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor Remnant save files and back them up when they&apos;re changed.
        /// </summary>
        public static string chkAutoBackup_ToolTip {
            get {
                return ResourceManager.GetString("chkAutoBackup_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically check for program update.
        /// </summary>
        public static string chkAutoCheckUpdate_Content {
            get {
                return ResourceManager.GetString("chkAutoCheckUpdate_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto hide Navigation and TitleBar when inactive.
        /// </summary>
        public static string chkAutoHideNaviAndTitleBar_Content {
            get {
                return ResourceManager.GetString("chkAutoHideNaviAndTitleBar_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create log file.
        /// </summary>
        public static string chkCreateLogFile_Content {
            get {
                return ResourceManager.GetString("chkCreateLogFile_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether a log.txt file should be created.
        /// </summary>
        public static string chkCreateLogFile_ToolTip {
            get {
                return ResourceManager.GetString("chkCreateLogFile_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug prerequisites.
        /// </summary>
        public static string chkDebugPrerequisites {
            get {
                return ResourceManager.GetString("chkDebugPrerequisites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump Analyzer data structures to analyzer.json .
        /// </summary>
        public static string chkDumpAnalyzerJson {
            get {
                return ResourceManager.GetString("chkDumpAnalyzerJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When exporting, export copies of saves.
        /// </summary>
        public static string chkExportCopy_Content {
            get {
                return ResourceManager.GetString("chkExportCopy_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When exporting, export decompressed saves.
        /// </summary>
        public static string chkExportDecoded_Content {
            get {
                return ResourceManager.GetString("chkExportDecoded_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When exporting, export saves in json format.
        /// </summary>
        public static string chkExportJson_Content {
            get {
                return ResourceManager.GetString("chkExportJson_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only when inactive.
        /// </summary>
        public static string chkOnlyInactive_Content {
            get {
                return ResourceManager.GetString("chkOnlyInactive_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Opacity.
        /// </summary>
        public static string chkOpacity_Content {
            get {
                return ResourceManager.GetString("chkOpacity_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Experimental, might cause instability).
        /// </summary>
        public static string chkOpacity_note_Text {
            get {
                return ResourceManager.GetString("chkOpacity_note_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report parser warnings.
        /// </summary>
        public static string chkReportParserWarnings {
            get {
                return ResourceManager.GetString("chkReportParserWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Performance metrics.
        /// </summary>
        public static string chkReportPerformance {
            get {
                return ResourceManager.GetString("chkReportPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Player debug info.
        /// </summary>
        public static string chkReportPlayerInfo {
            get {
                return ResourceManager.GetString("chkReportPlayerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show zone connections.
        /// </summary>
        public static string chkShowConnections_Content {
            get {
                return ResourceManager.GetString("chkShowConnections_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show co-op items.
        /// </summary>
        public static string chkShowCoopItems_Content {
            get {
                return ResourceManager.GetString("chkShowCoopItems_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show items from The Awakened King DLC.
        /// </summary>
        public static string chkShowDlc1 {
            get {
                return ResourceManager.GetString("chkShowDlc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show items from The Forgotten Kingdom DLC.
        /// </summary>
        public static string chkShowDlc2 {
            get {
                return ResourceManager.GetString("chkShowDlc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show campaign/adventure items with a missing prerequisite that did not roll in the compaign/adventure.
        /// </summary>
        public static string chkShowItemsWithNoPrereqs {
            get {
                return ResourceManager.GetString("chkShowItemsWithNoPrereqs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Labyrinth items.
        /// </summary>
        public static string chkShowLabyrinth_Content {
            get {
                return ResourceManager.GetString("chkShowLabyrinth_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show looted world drops / boss rewards.
        /// </summary>
        public static string chkShowLootedItems_Content {
            get {
                return ResourceManager.GetString("chkShowLootedItems_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Possible Items column.
        /// </summary>
        public static string chkShowPossibleItems_Content {
            get {
                return ResourceManager.GetString("chkShowPossibleItems_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Root Earth items.
        /// </summary>
        public static string chkShowRootEarth_Content {
            get {
                return ResourceManager.GetString("chkShowRootEarth_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Simulacrums.
        /// </summary>
        public static string chkShowSimulacrums_Content {
            get {
                return ResourceManager.GetString("chkShowSimulacrums_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tomes of Knowledge.
        /// </summary>
        public static string chkShowTomes_Content {
            get {
                return ResourceManager.GetString("chkShowTomes_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Ward 13 items.
        /// </summary>
        public static string chkShowWard13_Content {
            get {
                return ResourceManager.GetString("chkShowWard13_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show world stones.
        /// </summary>
        public static string chkShowWorldStones_Content {
            get {
                return ResourceManager.GetString("chkShowWorldStones_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a backup to restore from the list..
        /// </summary>
        public static string Choose_a_backup_to_restore_from_the_list_ {
            get {
                return ResourceManager.GetString("Choose a backup to restore from the list.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        public static string Collapse_All {
            get {
                return ResourceManager.GetString("Collapse All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string Confirm_Delete {
            get {
                return ResourceManager.GetString("Confirm Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string Connections {
            get {
                return ResourceManager.GetString("Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find save file location; please set manually.
        /// </summary>
        public static string Could_not_find_save_file_location__please_set_manually {
            get {
                return ResourceManager.GetString("Could not find save file location; please set manually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Enabling these could cause performance degradation and flood the logs).
        /// </summary>
        public static string debug_note {
            get {
                return ResourceManager.GetString("debug_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting excess backup.
        /// </summary>
        public static string Deleting_excess_backup {
            get {
                return ResourceManager.GetString("Deleting excess backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to move your backups to this new folder?.
        /// </summary>
        public static string Do_you_want_to_move_your_backups_to_this_new_folder_ {
            get {
                return ResourceManager.GetString("Do you want to move your backups to this new folder?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking for new game info.
        /// </summary>
        public static string Error_checking_for_new_game_info {
            get {
                return ResourceManager.GetString("Error checking for new game info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking for new version.
        /// </summary>
        public static string Error_checking_for_new_version {
            get {
                return ResourceManager.GetString("Error checking for new version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error exporting save files: {errorMessage}.
        /// </summary>
        public static string Error_exporting_save_files___errorMessage_ {
            get {
                return ResourceManager.GetString("Error exporting save files: {errorMessage}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the game before restoring a save backup..
        /// </summary>
        public static string Exit_the_game_before_restoring_a_save_backup_ {
            get {
                return ResourceManager.GetString("Exit the game before restoring a save backup.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        public static string Expand_All {
            get {
                return ResourceManager.GetString("Expand All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export save files.
        /// </summary>
        public static string Export_save_files_as_plaintext {
            get {
                return ResourceManager.GetString("Export save files as plaintext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot export to your save folder or a folder containing save backups..
        /// </summary>
        public static string export_save_invalid_folder_error {
            get {
                return ResourceManager.GetString("export_save_invalid_folder_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fextralife Wiki.
        /// </summary>
        public static string Fextralife {
            get {
                return ResourceManager.GetString("Fextralife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Folder.
        /// </summary>
        public static string Game_Folder {
            get {
                return ResourceManager.GetString("Game Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game info updated..
        /// </summary>
        public static string Game_info_updated_ {
            get {
                return ResourceManager.GetString("Game info updated.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardcore.
        /// </summary>
        public static string Hardcore {
            get {
                return ResourceManager.GetString("Hardcore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not import save; backup with that timestamp already exists.
        /// </summary>
        public static string Import_failed_backup_exists {
            get {
                return ResourceManager.GetString("Import_failed_backup_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save successfully imported to backups.
        /// </summary>
        public static string Import_save_success {
            get {
                return ResourceManager.GetString("Import_save_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid backup restore type.
        /// </summary>
        public static string Invalid_backup_restore_type {
            get {
                return ResourceManager.GetString("Invalid backup restore type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Folder.
        /// </summary>
        public static string Invalid_Folder {
            get {
                return ResourceManager.GetString("Invalid Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid folder: Backup folder cannot be the game&apos;s save folder..
        /// </summary>
        public static string InvalidBackupFolderNoBackupsInSaves {
            get {
                return ResourceManager.GetString("InvalidBackupFolderNoBackupsInSaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid folder: Select where your Remnant II game is installed..
        /// </summary>
        public static string InvalidGameFolder {
            get {
                return ResourceManager.GetString("InvalidGameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid folder: Select where your Remnant II saves are stored.
        /// </summary>
        public static string InvalidSaveFolder {
            get {
                return ResourceManager.GetString("InvalidSaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid folder: Please select a folder other than the backup folder..
        /// </summary>
        public static string InvalidSaveFolderNoSavesInBackups {
            get {
                return ResourceManager.GetString("InvalidSaveFolderNoSavesInBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep.
        /// </summary>
        public static string Keep {
            get {
                return ResourceManager.GetString("Keep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language changed to {chosenLanguage}. You may have to restart to app for the change to fully apply..
        /// </summary>
        public static string Language_change_notice__chosenLanguage_ {
            get {
                return ResourceManager.GetString("Language_change_notice_{chosenLanguage}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last backup save date.
        /// </summary>
        public static string Last_backup_save_date {
            get {
                return ResourceManager.GetString("Last backup save date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups to keep (0 for unlimited).
        /// </summary>
        public static string lblBackupLimit_Text {
            get {
                return ResourceManager.GetString("lblBackupLimit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When your number of backups reaches this number, backups will automatically be deleted starting with the oldest.
        /// </summary>
        public static string lblBackupLimit_ToolTip {
            get {
                return ResourceManager.GetString("lblBackupLimit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes between backups.
        /// </summary>
        public static string lblBackupMins_Text {
            get {
                return ResourceManager.GetString("lblBackupMins_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum amount of time that must have passed since last backup before a new backup is made.
        /// </summary>
        public static string lblBackupMins_ToolTip {
            get {
                return ResourceManager.GetString("lblBackupMins_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log level.
        /// </summary>
        public static string lblLogLevel {
            get {
                return ResourceManager.GetString("lblLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World analyzer looted world drops / boss rewards color.
        /// </summary>
        public static string lblLootedItemColor {
            get {
                return ResourceManager.GetString("lblLootedItemColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World analzyer missing item color.
        /// </summary>
        public static string lblMissingItemColor_Text {
            get {
                return ResourceManager.GetString("lblMissingItemColor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        public static string lblOpacitySlider_Text {
            get {
                return ResourceManager.GetString("lblOpacitySlider_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start page.
        /// </summary>
        public static string lblStartPage_Text {
            get {
                return ResourceManager.GetString("lblStartPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which page to load on app start.
        /// </summary>
        public static string lblStartPage_ToolTip {
            get {
                return ResourceManager.GetString("lblStartPage_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string lblSwitchLanguage_Text {
            get {
                return ResourceManager.GetString("lblSwitchLanguage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Wiki.
        /// </summary>
        public static string lblWiki_Text {
            get {
                return ResourceManager.GetString("lblWiki_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which wiki to load for item lookup.
        /// </summary>
        public static string lblWiki_ToolTip {
            get {
                return ResourceManager.GetString("lblWiki_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Not all items can be detected as looted).
        /// </summary>
        public static string looted_note {
            get {
                return ResourceManager.GetString("looted_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Backup.
        /// </summary>
        public static string menuRestore_Header {
            get {
                return ResourceManager.GetString("menuRestore_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything.
        /// </summary>
        public static string menuRestoreAll_Header {
            get {
                return ResourceManager.GetString("menuRestoreAll_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters Only.
        /// </summary>
        public static string menuRestoreCharacters_Header {
            get {
                return ResourceManager.GetString("menuRestoreCharacters_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worlds Only.
        /// </summary>
        public static string menuRestoreWorlds_Header {
            get {
                return ResourceManager.GetString("menuRestoreWorlds_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Items.
        /// </summary>
        public static string Missing_Items {
            get {
                return ResourceManager.GetString("Missing Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Backups.
        /// </summary>
        public static string Move_Backups {
            get {
                return ResourceManager.GetString("Move Backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available!.
        /// </summary>
        public static string New_version_available_ {
            get {
                return ResourceManager.GetString("New version available!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The files must include a profile.sav.
        /// </summary>
        public static string No_profile_sav_found_warning {
            get {
                return ResourceManager.GetString("No_profile_sav_found_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The files must include at least one save_#.sav file.
        /// </summary>
        public static string No_world_found_warning {
            get {
                return ResourceManager.GetString("No_world_found_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window opacity is changed. You have to restart app for the change to apply..
        /// </summary>
        public static string Opacity_toggle_notice {
            get {
                return ResourceManager.GetString("Opacity_toggle_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string Open_Folder {
            get {
                return ResourceManager.GetString("Open Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open wiki.
        /// </summary>
        public static string Open_wiki {
            get {
                return ResourceManager.GetString("Open wiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one export options in profile.
        /// </summary>
        public static string Please_select_at_least_one_export_options_in_profile {
            get {
                return ResourceManager.GetString("Please select at least one export options in profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible Items.
        /// </summary>
        public static string Possible_Items {
            get {
                return ResourceManager.GetString("Possible Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processing save file change.
        /// </summary>
        public static string processing_save_file_change {
            get {
                return ResourceManager.GetString("processing save file change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progression.
        /// </summary>
        public static string Progression {
            get {
                return ResourceManager.GetString("Progression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remnant.wiki.
        /// </summary>
        public static string RemnantWiki {
            get {
                return ResourceManager.GetString("RemnantWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Backups.
        /// </summary>
        public static string Save_Backups {
            get {
                return ResourceManager.GetString("Save Backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save change detected; waiting {numMinutes} minutes until next backup.
        /// </summary>
        public static string Save_change_detected__waiting__numMinutes__minutes_until_next_backup {
            get {
                return ResourceManager.GetString("Save change detected; waiting {numMinutes} minutes until next backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file in use; waiting 0.5 seconds and retrying..
        /// </summary>
        public static string Save_file_in_use__waiting_0_5_seconds_and_retrying_ {
            get {
                return ResourceManager.GetString("Save file in use; waiting 0.5 seconds and retrying.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Folder.
        /// </summary>
        public static string Save_Folder {
            get {
                return ResourceManager.GetString("Save Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save plaintext data.
        /// </summary>
        public static string Save_plaintext_data {
            get {
                return ResourceManager.GetString("Save plaintext data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Date.
        /// </summary>
        public static string SaveDate {
            get {
                return ResourceManager.GetString("SaveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves.
        /// </summary>
        public static string Saves {
            get {
                return ResourceManager.GetString("Saves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder other than the game&apos;s save folder..
        /// </summary>
        public static string Select_a_folder_other_than_the_game_s_save_folder_ {
            get {
                return ResourceManager.GetString("Select a folder other than the game\'s save folder.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setting save file timer.
        /// </summary>
        public static string setting_save_file_timer {
            get {
                return ResourceManager.GetString("setting save file timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survival.
        /// </summary>
        public static string Survival {
            get {
                return ResourceManager.GetString("Survival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string Text_Debug {
            get {
                return ResourceManager.GetString("Text_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dim.
        /// </summary>
        public static string Text_Dim {
            get {
                return ResourceManager.GetString("Text_Dim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Text_Error {
            get {
                return ResourceManager.GetString("Text_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal.
        /// </summary>
        public static string Text_Fatal {
            get {
                return ResourceManager.GetString("Text_Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string Text_Highlight {
            get {
                return ResourceManager.GetString("Text_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Text_Information {
            get {
                return ResourceManager.GetString("Text_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Text_Normal {
            get {
                return ResourceManager.GetString("Text_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose.
        /// </summary>
        public static string Text_Verbose {
            get {
                return ResourceManager.GetString("Text_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Text_Warning {
            get {
                return ResourceManager.GetString("Text_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latest version of Remnant 2 Save Analyzer is {CurrentVersion}. You are using version {LocalVersion}. Do you want to upgrade the application now?.
        /// </summary>
        public static string The_latest_version_of_Remnant_2_Save_Analyzer_is__CurrentVersion___You_are_using_version__LocalVersion___Do_you_want_to_upgrade_the_application_now_ {
            get {
                return ResourceManager.GetString("The latest version of Remnant 2 Save Analyzer is {CurrentVersion}. You are using " +
                        "version {LocalVersion}. Do you want to upgrade the application now?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The world analyzer found {numberOfEventGroups} groups of events, but it expects a maximum of 2. Things might not work as intended..
        /// </summary>
        public static string Unexpected_event_group_number_warning__numberOfEventGroups_ {
            get {
                return ResourceManager.GetString("Unexpected_event_group_number_warning_{numberOfEventGroups}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized files found in save folder: {fileList}. These files may interfere with the world analyzer..
        /// </summary>
        public static string Unrecognized_save_files_warning__fileList_ {
            get {
                return ResourceManager.GetString("Unrecognized_save_files_warning_{fileList}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Analyzer.
        /// </summary>
        public static string World_Analyzer {
            get {
                return ResourceManager.GetString("World Analyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Stones.
        /// </summary>
        public static string World_Stones {
            get {
                return ResourceManager.GetString("World Stones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by events or items.
        /// </summary>
        public static string WorldAnalyzerFilter_PlaceholderText {
            get {
                return ResourceManager.GetString("WorldAnalyzerFilter_PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must wait 5 minutes between update checks.
        /// </summary>
        public static string You_must_wait_5_minutes_between_update_checks {
            get {
                return ResourceManager.GetString("You must wait 5 minutes between update checks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
